From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 235ebc2] Automated Server Update
 2 files changed, 13 insertions(+)
 create mode 100644 dailyserverlogfile.log
To https://github.com/cookeda/CapstoneSportsbook.git
   983b708..235ebc2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("./Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: './Data Collecting Src'
[main b22e7c9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   78a75c1..b22e7c9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6f86681] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b48dd0e..6f86681  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main b1f0102] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0035e5f..b1f0102  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 300a56d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   cc9fc99..300a56d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 77de77da] Automated Server Update
 2 files changed, 14 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   34b14411..77de77da  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7186f7f5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   288e32a0..7186f7f5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main d5aa4cb5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   76186943..d5aa4cb5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1e3c28bf] Automated Server Update
 1 file changed, 9 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e50d317a..1e3c28bf  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7571386c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ee88608a..7571386c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6e477ce9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fcf15881..6e477ce9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5c971fe1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4deeba63..5c971fe1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 796a434e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0eb8705f..796a434e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6fd483dd] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   69c53831..6fd483dd  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f31b96e0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bbf9d147..f31b96e0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c75a8b3c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   23248d0b..c75a8b3c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 31612210] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   627c916a..31612210  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a34410f7] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fd702158..a34410f7  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5080586e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ab15588d..5080586e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 85cedd1b] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8260abc9..85cedd1b  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb2a7e8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9aceffbb..acb2a7e8  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3aa40f17] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   dc562c28..3aa40f17  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4c38cf94] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c13b2a7a..4c38cf94  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb0b5b1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e306f159..acb0b5b1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4a500c1c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c826b884..4a500c1c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f81ecc59] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b1785bea..f81ecc59  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2f4e4f42] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   148fc2cb..2f4e4f42  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 345592d2] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8b92c33e..345592d2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 78c29d25] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0cdff6f6..78c29d25  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3cd6073f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   2b95a9ad..3cd6073f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f40c27a1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0807867b..f40c27a1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 434e839c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4a3ae257..434e839c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 9fd4d736] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d1ccd191..9fd4d736  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 224f3e97] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   5efe9816..224f3e97  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 8135b720] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7f6fcc6d..8135b720  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main dbc406ed] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4610065f..dbc406ed  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a14edaf9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   60ae19be..a14edaf9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2748716f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   44887ff9..2748716f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 98f4cdd8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   58003d7a..98f4cdd8  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a4f87a14] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e76574fe..a4f87a14  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 86b08f32] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c10caa09..86b08f32  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main b515ec8c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   a7620bc2..b515ec8c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 43f9eb30] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bfda57fe..43f9eb30  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3e80d0bb] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8b749ae5..3e80d0bb  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a8682ca3] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   cbdcbe06..a8682ca3  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1fda108a] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   6a027d59..1fda108a  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 69668458] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   488a7259..69668458  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main bdf0f400] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b2c54e4a..bdf0f400  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3760ad53] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e5442c2f..3760ad53  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a0eac588] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9c65686a..a0eac588  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 206314d1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d23c1481..206314d1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c8d690d0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b6709e21..c8d690d0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main fea60b70] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   f2e1f9ef..fea60b70  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 017c8fea] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   3b774731..017c8fea  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main ec8c36b1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bc8fe2d6..ec8c36b1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main deb8be3e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0c78f341..deb8be3e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 42260cc5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e99c92e8..42260cc5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 9700229a7] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   07571d617..9700229a7  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 895d07ce5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   14adb0ace..895d07ce5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main eef3ac459] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   52d78f1bb..eef3ac459  main -> main
fatal: unable to access 'https://github.com/cookeda/CapstoneSportsbook.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main d5345bed0] Automated Server Update
 2 files changed, 10 insertions(+)
fatal: unable to access 'https://github.com/cookeda/CapstoneSportsbook.git/': Could not resolve host: github.com
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1db10a804] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9f16b9955..1db10a804  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main d76f79151] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7aa95733d..d76f79151  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main e1991a5ab] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fdd281c8f..e1991a5ab  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4c8c034ec] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   20a20aa1f..4c8c034ec  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 216e8111a] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   61de697fe..216e8111a  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4f6a47ab0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   492dea9b1..4f6a47ab0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 48f7e446d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   6fd674af4..48f7e446d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 533842b76] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   979a38c23..533842b76  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main bf6907fd0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c2af1a1fd..bf6907fd0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main aa3933b81] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d40feca52..aa3933b81  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main da56319dc] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8d6faed68..da56319dc  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 396adb548] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9bed472c2..396adb548  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 406b200f0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7855b212b..406b200f0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 97915c882] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ea9d68e6a..97915c882  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 95ea60af7] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   f1f8e6451..95ea60af7  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 8a3edafab] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   5a0971cdf..8a3edafab  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2769632db] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   be9f452e9..2769632db  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 75b669bc4] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   1a6701346..75b669bc4  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1f583ca4f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4bd26cb7d..1f583ca4f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3743cb75d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   893f3dc8c..3743cb75d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main e37fbe877] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   f72b347b1..e37fbe877  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 74c03d47d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7d6881ad6..74c03d47d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 39f1ebed2] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   33504fa2a..39f1ebed2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main ff2ec4b2d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   a6d6ae922..ff2ec4b2d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 319983912] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   70fce32ed..319983912  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c68cdaa11] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8e0908a58..c68cdaa11  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 67a155824] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   a6e9a276a..67a155824  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a87bc34ef] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   6b636f513..a87bc34ef  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main bb30654d0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7815ffbf0..bb30654d0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 9941c7a0e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4bfb0575b..9941c7a0e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 00cff686d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   521e0b2ba..00cff686d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1eea10a13] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   054043adf..1eea10a13  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 092f9d859] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fab4769ba..092f9d859  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 662f0ac0c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e19ab6ad8..662f0ac0c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 244ae3f59] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   369d64d1a..244ae3f59  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main e5de98c5b] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   3d031750c..e5de98c5b  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 36828346f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b34f4611f..36828346f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 68962ec43] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   22eba01c2..68962ec43  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 88924cd4c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   1a41848b0..88924cd4c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5c7eee994] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c413a9ea3..5c7eee994  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 13d85c62d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   053723e9d..13d85c62d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c0b39e651] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d58908771..c0b39e651  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main ac89cea35] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7756cc4ed..ac89cea35  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main e9d754787] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d1ba6301e..e9d754787  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c1416c6fb] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d9f8525ec..c1416c6fb  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a3481c57c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   3038aca3d..a3481c57c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1bf348f3b] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   be4a744d6..1bf348f3b  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 749996fb2] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d9f0053ec..749996fb2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 0a22e5e32] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   880360073..0a22e5e32  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch                main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main fbdec75a8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c631939ab..fbdec75a8  main -> main
